#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
runtests - Run the project tests

Usage:
  runtests --travis
  runtests (--all | --unit | --integration)
  runtests --help
  runtests --version

Options:
  --repeat-url           Use the same url concurrently.
  -v --version           Show version.
"""
from __future__ import division, absolute_import, print_function
import os
import sys
from docopt import docopt

os.environ.setdefault("FRAPPE_TEST", "1")

UNIT_OPTS = [
    "tests/unit/",
    "--with-doctest",
    "recommendation/util.py",
    "recommendation/core.py",
    "recommendation/models.py"
]
INTEGRATION_OPTS = ["tests/integration/"]


def main():
    opts = docopt(__doc__, version="Frappé tests 1.0")
    if opts["--travis"]:
        os.environ.setdefault("REUSE_DB", "1")
        if os.environ["TRAVIS_BRANCH"] == "master":
            opts["--integration"] = True
        opts["--unit"] = True
    if opts["--all"]:
        opts["--integration"] = opts["--unit"] = True
    sys.argv = sys.argv[:1]
    OPTIONS = []
    if opts["--unit"]:
        os.environ["DJANGO_SETTINGS_MODULE"] = "recommendation.settings.unit.settings"
        OPTIONS += UNIT_OPTS
    if opts["--integration"]:
        os.environ["DJANGO_SETTINGS_MODULE"] = "recommendation.settings.integration.settings"
        OPTIONS += INTEGRATION_OPTS
        
    import django
    if django.VERSION > (1, 6):
      django.setup()
    from django.core.management import call_command
    call_command(*(["test", "--verbosity=2", "--with-id"] + OPTIONS))


if __name__ == "__main__":
    main()
