#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
runtests - Run the project tests

Usage:
  runtests --travis
  runtests (--all | --unit | --integration)
  runtests --help
  runtests --version

Options:
  --repeat-url           Use the same url concurrently.
  -v --version           Show version.
"""

import os
import sys
import subprocess
from docopt import docopt
from pkg_resources import resource_filename

UNIT_OPTS = "tests/unit/ --with-doctest recommendation/util.py recommendation/core.py recommendation/models.py"
INTEGRATION_OPTS = "tests/integration/"


def main():
    opts = docopt(__doc__, version="Frappé tests 1.0")
    if opts["--travis"]:
        if os.environ["TRAVIS_BRANCH"] == "master":
            opts["--all"] = True
        else:
            opts["--unit"] = True

    if opts["--unit"]:
        command = "echo yes | %s" % resource_filename(__name__, "/../src/manage.py test -v2 --with-id %s" % UNIT_OPTS)
    elif opts["--integration"]:
        command = "echo yes | %s" % resource_filename(__name__, "/../src/manage.py test -v2 --with-id %s" %
                                                      INTEGRATION_OPTS)
    else:
        command = "echo yes | %s" % resource_filename(__name__, "/../src/manage.py test -v2 --with-id %s %s" %
                                                     (INTEGRATION_OPTS, UNIT_OPTS))
    exit(subprocess.call(command, stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr, shell=True))


if __name__ == "__main__":
    main()